const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  detectSteam: () => ipcRenderer.invoke('detect-steam'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  discoverMods: (config) => ipcRenderer.invoke('discover-mods', config),
  saveLoadOrder: (data) => ipcRenderer.invoke('save-load-order', data),
  getPacks: () => ipcRenderer.invoke('get-packs'),
  savePack: (pack) => ipcRenderer.invoke('save-pack', pack),
  deletePack: (name) => ipcRenderer.invoke('delete-pack', name),
  fetchWorkshopDetails: (ids) => ipcRenderer.invoke('fetch-workshop-details', ids),
  loadModDatabase: () => ipcRenderer.invoke('load-mod-database'),
  saveModDatabase: (data) => ipcRenderer.invoke('save-mod-database', data),
  openFileDialog: (filters) => ipcRenderer.invoke('open-file-dialog', filters),
  saveFileDialog: (name) => ipcRenderer.invoke('save-file-dialog', name),
  writeFile: (path, content) => ipcRenderer.invoke('write-file', path, content),
  generateConflicts: (activeMods) => ipcRenderer.invoke('generate-conflicts', activeMods),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  downloadUpdate: (url) => ipcRenderer.invoke('download-update', url),
  launchGame: (gamePath) => ipcRenderer.invoke('launch-game', gamePath),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  showInFolder: (filePath) => ipcRenderer.invoke('show-in-folder', filePath),
});
